package DealershipProject;

// Challenge 1 Add a method inside Cars called displayDetails() that prints a single car's color and model.
// Challenge 2 Add an instance variable int mileage and a method drive(int miles) that increases the car's mileage.
// Challenge 3 In your main method, instantiate three cars, call drive() on two of them, and output both individual car stats and the total fleet count using Cars.totalNumberOfCars.
// Challenges generated by Google Gemini

public class DealershipInventorySystem {

}
